### ISSUE TITLE
compatibility with aetherium elites

### ISSUE THREAD

**Issue by ConqAra** [CuteDoge01/ArtifactOfChosenMod#1]
is there compatibility for aetherium's elite aspect?

**Comment by CuteDoge01** [comment]
Oh yeah, you are right, the support for those is back in ZetAspects. I have added this one too, you should be able to download version 1.0.4 in a few minutes. Haven't done the tests but should work as the mod is simple. Report if any issues

**Comment by ConqAra** [comment]
seems to work fine 👍
