### ISSUE TITLE
When artifact is turned off, this happens

### ISSUE THREAD

**Issue by ConqAra** [CuteDoge01/ArtifactOfChosenMod#3]
![image](https://user-images.githubusercontent.com/76233356/172063996-0cc15ca9-a08a-4a6a-9761-669a11ce0ec8.png)
I don't think think this error should be said in chat when you have the artifact off.

**Comment by CuteDoge01** [comment]
I see, makes sense, check out the new version in a few mins

Again, thank you so much actually playing with it and helping with development
